### ISSUE TITLE
Sbt error when opening the project  

### ISSUE THREAD

**Issue by gigiigig** [typelead/sbt-eta#7]
Hi,

I'm trying to use the plugin inside an existing sbt project, but  keep getting this error:
```
[error] [etlas] etlas: Expected exactly one target as an argument, see `etlas deps --help`.
java.lang.RuntimeException:

 [etlas] Exit Failure 1
	at scala.sys.package$.error(package.scala:27)
	at com.typelead.SbtEta$.etlas(SbtEta.scala:114)
	at com.typelead.SbtEta$$anonfun$7.apply(SbtEta.scala:57)
	at com.typelead.SbtEta$$anonfun$7.apply(SbtEta.scala:51)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
	at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
	at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitEvaluate$1.apply$mcV$sp(INode.scala:69)
	at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala:78)
	at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
also tried with a fresh project, the one in the example and get the same.  

Cheers,
Luigi

**Comment by rahulmutt** [comment]
This is an issue you'll get with the most recent versions of `etlas` since there was a breaking change. I assume you have `etlas >= 1.1` installed?

One workaround for now is to use an older version of `etlas`. You can take the link you get from the main Eta website and replace `etlas-1.1.0.0` with `etlas-1.0.2.0` in the link to get the older one for your platform.

**Comment by gigiigig** [comment]
Hi @rahulmutt thanks for the quick answer, should this be part of the documentation? It is misleading at the moment, it says: 

```
Prerequisites

Etlas >= 1.0.2.0
```

**Comment by rahulmutt** [comment]
Yes you're right! I changed it just now to indicate that 1.1.0.0 doesn't work anymore.

**Comment by gigiigig** [comment]
@rahulmutt It's working now with `1.0.2.0` , is there any plan to update the plugin to the new version?

**Comment by rahulmutt** [comment]
Yes there is. I'll schedule a time slot to work on this sometime within the next week.

**Comment by gigiigig** [comment]
Cool 👍 , thanks!
